### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pustovitDmytro** [pustovitDmytro/rest-chronicle#5]
- [ ] add cls context resolve
- [ ] enhance docs
- [ ] swagger array data type
- [x] swagger multiple responses handle
- [ ] slate
- [x] raml
